backend_opset_version = {
    'ATen': [],
    'Abs': [1, 6],
    'Acos': [7],
    'Add': [1, 6, 7],
    'Affine': [],
    'And': [1, 7],
    'ArgMax': [1],
    'ArgMin': [1],
    'Asin': [7],
    'Atan': [7],
    'AveragePool': [1, 7],
    'BatchNormalization': [1, 6, 7],
    'Cast': [1, 6],
    'Ceil': [1, 6],
    'Clip': [1, 6],
    'Concat': [1, 4],
    'Constant': [1, 9],
    'ConstantFill': [1],
    'ConstantLike': [9],
    'Conv': [1],
    'ConvTranspose': [1],
    'Cos': [7],
    'Crop': [],
    'DepthToSpace': [1],
    'Div': [1, 6, 7],
    'Dropout': [1, 6, 7],
    'DynamicSlice': [9],
    'Elu': [1, 6],
    'Equal': [1, 7],
    'Exp': [1, 6],
    'Expand': [8],
    'EyeLike': [9],
    'Flatten': [1, 9],
    'Floor': [1, 6],
    'GRU': [1, 3, 7],
    'GRUUnit': [],
    'Gather': [1],
    'Gemm': [1, 6, 7, 9],
    'GivenTensorFill': [],
    'GlobalAveragePool': [1],
    'GlobalLpPool': [1, 2],
    'GlobalMaxPool': [1],
    'Greater': [1, 7, 9],
    'HardSigmoid': [1, 6],
    'Hardmax': [1],
    'Identity': [1],
    'If': [],
    'ImageScaler': [1],
    'InstanceNormalization': [1, 6],
    'LRN': [1],
    'LSTM': [1, 7],
    'LeakyRelu': [1, 6],
    'Less': [1, 7, 9],
    'Log': [1, 6],
    'LogSoftmax': [1],
    'Loop': [],
    'LpNormalization': [1],
    'LpPool': [],
    'MatMul': [1, 9],
    'Max': [1, 6, 8],
    'MaxPool': [1, 8],
    'MaxRoiPool': [],
    'Mean': [1, 6, 8],
    'MeanVarianceNormalization': [1],
    'Min': [1, 6, 8],
    'Mul': [1, 6, 7],
    'Multinomial': [],
    'Neg': [1, 6],
    'Not': [1],
    'Or': [1, 7],
    'PRelu': [1, 6, 7, 9],
    'Pad': [1, 2],
    'ParametricSoftplus': [],
    'Pow': [1, 7],
    'RNN': [1, 7],
    'RandomNormal': [1],
    'RandomNormalLike': [1],
    'RandomUniform': [1],
    'RandomUniformLike': [1],
    'Reciprocal': [1, 6],
    'ReduceL1': [1],
    'ReduceL2': [1],
    'ReduceLogSum': [1],
    'ReduceLogSumExp': [1],
    'ReduceMax': [1],
    'ReduceMean': [1],
    'ReduceMin': [1],
    'ReduceProd': [1],
    'ReduceSum': [1],
    'ReduceSumSquare': [1],
    'Relu': [1, 6],
    'Reshape': [1, 5],
    'Scale': [],
    'ScaledTanh': [],
    'Scan': [],
    'Selu': [1, 6],
    'Shape': [1],
    'Sigmoid': [1, 6],
    'Sin': [7],
    'Size': [1],
    'Slice': [1],
    'Softmax': [1],
    'Softplus': [1],
    'Softsign': [1],
    'SpaceToDepth': [1],
    'Split': [1, 2],
    'Sqrt': [1, 6],
    'Squeeze': [1],
    'Sub': [1, 6, 7],
    'Sum': [1, 6, 8],
    'Tan': [7],
    'Tanh': [1, 6],
    'ThresholdedRelu': [1],
    'Tile': [1, 6],
    'TopK': [1],
    'Transpose': [1],
    'Unsqueeze': [1],
    'Upsample': [7],
    'Xor': [1, 7]
}